stages:         
  - build
  - test
  - deploy

build:       
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

test:   
  stage: test    
  script:
    - echo "Running unit tests... This will take about 60 seconds."


deploy:      
  stage: deploy 
  script:
    - echo "Deploying application..."
 
