version: '3.3'

services:
  DH-back:
    image: openjdk:18-jdk-alpine3.15
    restart: always
    volumes:
      - ./app.jar:/app.jar
    ports:
      - "8080:8080"
    entrypoint: ["java", "-jar", "/app.jar", "-Pprod"]
    environment:
      - EMAILUSER=value
      - EMAILPASS=value
      - CUENTAENVIO=value
      - SECRET=value